# Generated by Django 5.2 on 2025-04-14 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(max_length=255)),
                ('knowledge_level', models.CharField(choices=[('E', 'Elementary level or juniour level'), ('B', 'Basic level or juniour plus level'), ('A', 'Average level or middle level'), ('I', 'Advanced knowledge or middle plus level'), ('U', 'Mastered knowledge of basic and some advanced knowledge or seniour minus level'), ('C', 'Complex knowledge or seniour level'), ('P', 'Mastered everything in specific knowledge or seniour plus level')], max_length=1)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('E', 'Elementary level or juniour level'), ('B', 'Basic level or juniour plus level'), ('A', 'Average level or middle level'), ('I', 'Advanced knowledge or middle plus level'), ('U', 'Mastered knowledge of basic and some advanced knowledge or seniour minus level'), ('C', 'Complex knowledge or seniour level'), ('P', 'Mastered everything in specific knowledge or seniour plus level')], max_length=1, verbose_name='specific_knowlegde')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_with_skill', to='skills.skills')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_skilled', to='users.profile')),
            ],
            options={
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
